openapi: 3.0.3
info:
  title: ProductPrice
  description: |-
    This is a simple API to get Product Prices
  termsOfService: http://swagger.io/terms/
  contact:
    email: iicc96@hotmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/api/v1
paths:
  /productprices/search:
    get:
      tags:
        - getProductPricesByCriteria
      summary: get product prices by criteria
      description: get product prices by criteria
      operationId: getProductPricesByCriteria
      parameters:
        - in: query
          name: applicationDate
          description: fecha de aplicacion
          required: true
          schema:
            type: string
            format: date-time
            pattern: '^(?!\s*$).+'
        - in: query
          name: productId
          description: product id
          required: true
          schema:
            type: string
            pattern: '^(?!\s*$).+'
        - in: query
          name: brandId
          description: brand id
          required: true
          schema:
            type: string
            pattern: '^(?!\s*$).+'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPriceDTO'
        '400':
          description: Bad request. Invalid input
        '422':
          description: Unprocessable Entity.
        '404':
          description: A price with the specified parameters was not found.
components:
  schemas:
    ProductPriceDTO:
      type: object
      properties:
        productId:
          type: string
          description: product id
        brandId:
          type: string
          description: brand id
        priceList:
          type: integer
          description: tarifa a aplicar
        startDate:
          type: string
          format: date-time
          description: fecha inicial de la aplicacion
        endDate:
          type: string
          format: date-time
          description: fecha final de la aplicacion
        price:
          type: number
          description: precio final a aplicar
      xml:
        name: ProductPriceDTO