CREATE TABLE PRODUCT_PRICE (
    "ID" VARCHAR(36) NOT NULL,
    "BRAND_ID" VARCHAR(36) NOT NULL,
    "START_DATE" DATETIME NOT NULL,
    "END_DATE" DATETIME NOT NULL,
    "PRICE_LIST" NUMBER(10,0) NOT NULL,
    "PRODUCT_ID" VARCHAR(36) NOT NULL,
    "PRIORITY" NUMBER(10,0) NOT NULL,
    "PRICE" NUMBER(15,2) NOT NULL,
    "CURRENCY" NUMBER (2,0) NOT NULL
);